FROM rocker/r-ver:4

RUN apt-get update && apt-get install -y \
    libssl-dev \
    libcurl4-gnutls-dev \
    libxml2-dev \
    libudunits2-dev \
    libgdal-dev \
    pandoc 


# TODO: do I need pandoc? Do I need the python packages?

# R packages installing options
RUN echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.rstudio.com'; options(repos = r);" > ~/.Rprofile
# Install dependencies for running Calibra Curve, converting from XLSX to CSV and create reports (Quarto)
RUN R -e "install.packages(c('Rserve', 'openxlsx', 'rmarkdown', 'devtools', 'box'), lib = 'usr/local/lib/R/library')"
# Install visualization dependencies (including all 'plotly' dependencies: 'reticulate', 'jsonlite', 'kaleido' etc.)
RUN R -e "install.packages('plotly', lib = 'usr/local/lib/R/library', dependencies = TRUE)"

# Install Python
RUN apt-get install -y python3 python3-dev
# Install `kaleido` for PNG export
RUN R -e "reticulate::install_miniconda(force = TRUE); reticulate::conda_install('r-reticulate', 'python-kaleido'); reticulate::conda_install('r-reticulate', 'plotly', channel = 'plotly'); reticulate::use_miniconda('r-reticulate')"
RUN R -e 'write("reticulate::use_miniconda(\"r-reticulate\")",file=file.path(R.home(),"etc","Rprofile.site"),append=TRUE)'
